spring:
  application:
    name: chatbot
  h2.console.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only